name: "default"

template-configs:

  - name: once-files
    templates:

    - in: package.json
      out: package.json

    - in: packages/client/.spinrc.js
      out: packages/client/.spinrc.js
    - in: packages/server/.spinrc.js
      out: packages/server/.spinrc.js


    - in: packages/server/src/app.js
      out: packages/server/src/app.js


    - in: packages/client/src/modules/index.js
      out: packages/client/src/modules/index.js
    - in: packages/server/src/modules/index.ts
      out: packages/server/src/modules/index.ts
