name: "default"

template-configs:

  - name: once-files
    templates:

    - in: config/app.js
      out: config/app.js
    - in: config/analytics.js
      out: config/analytics.js
    - in: config/user.js
      out: config/user.js

