components:
  {{> client/components/designs/form-default.yaml}}
  {{> client/components/designs/view-default.yaml}}
  {{> client/components/designs/list-default.yaml}}
  {{> client/components/designs/table-default.yaml}}
